In [135]:
import pandas as pd
import numpy as np
import selenium
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import MoveTargetOutOfBoundsException
from selenium.common.exceptions import ElementClickInterceptedException
from selenium.common.exceptions import ElementNotInteractableException
from selenium.webdriver.common.action_chains import ActionChains
import time

In [147]:
driver=webdriver.Chrome(r"C:\Users\eshan\Downloads\chromedriver_win32\chromedriver.exe")

In [148]:
url="https://www.deccanherald.com/archives"
driver.get(url)
driver.maximize_window()

In [149]:
Date=[]
Author=[]
Vertical=[]
Headline=[]
Description=[]

In [151]:
def Details():
    links = [link.get_attribute('href') for link in driver.find_elements_by_xpath("//div[@class='group'][2]//div//div//ul//li//a")]
    for link in links:
        driver.get(link)
        time.sleep(3)
        driver.implicitly_wait(10)
    
        try:
            date=driver.find_element_by_xpath("//div[@class='article-author__time']//ul[@class='crud-items']//li[1]")
            dat=date.text
            Date.append(dat)
        except NoSuchElementException:
            Date.append('not available')
    
        try:
            author=driver.find_element_by_xpath("//div[@class='article-author__time']//span[1]")
            aut=author.text
            Author.append(aut)
        except NoSuchElementException:
            Author.append('not available')
    
        try:
            vertical=driver.find_element_by_xpath("//div[@class='section-container']//div//ul//li[2]//a")
            ver=vertical.text
            Vertical.append(ver)
        except NoSuchElementException:
            Vertical.append('not available')
        
        try:
            headline=driver.find_element_by_xpath("//div[@class='section-container']//div//ul//li[@class='last']")
            head=headline.text
            Headline.append(head)
        except NoSuchElementException:
            Headline.append('not available')
        
        try:
            description=driver.find_element_by_xpath("//div[@class='field field-name-body field-type-text-with-summary field-label-hidden']//div")
            des=description.text
            Description.append(des)  
        except NoSuchElementException:
            Description.append('not available')

In [152]:
def dates():
    date=driver.find_element_by_xpath("//div[@class='form-group']//a")
    driver.implicitly_wait(10)
    ActionChains(driver).move_to_element(date).click(date).perform()

    year=driver.find_element_by_xpath("//div[@class='numInputWrapper']//span[@class='arrowDown']")
    for x in range(4):
        year.click()
    
    month=driver.find_element_by_xpath("//span[@class='flatpickr-prev-month']")
    for x in range(6):
        month.click()

In [153]:
dates()
days=driver.find_elements_by_xpath("//div[@class='dayContainer']//span[@class='flatpickr-day ']")
number_of_days = len(days)
for x in range(29):
    day=driver.find_elements_by_xpath("//div[@class='dayContainer']//span[@class='flatpickr-day ']")[x]
    day.click()
    driver.implicitly_wait(10)
    try:       
        submit=driver.find_element_by_xpath("//a[@class='sanspro-semib datepicker-submit sq-horoscope-bg__button--black-bg sq-horoscope-bg__button']")
        submit.click()
    except StaleElementReferenceException:
        pass
    
      
    Details()
    
    try:
        driver.get(url)
    except StaleElementReferenceException:
        print('Refresh!')
        driver.refresh()
        driver.get(url)
        time.sleep(3)
    try:
        dates()
    except ElementNotInteractableException:
        driver.implicitly_wait(10)
        dates()

In [158]:
news=pd.DataFrame({})
news['Date']=Date
news['Author']=Author
news['Vertical']=Vertical
news['Headline']=Headline
news['Description']=Description

In [159]:
news

,Date,Author,Vertical,Headline,Description
0,"JUN 01 2016, 00:22 IST","NEW DELHI, Jun 01, 2016, DHNS:,",Business,No tax on cash buy of gold jewellery,"In a relief to jewellers and customers, the Ce..."
1,"JUN 01 2016, 08:27 IST","New Delhi, June 1, 2016, PTI:,",Business,"Petrol price up by Rs 2.58 per litre, diesel b...",Petrol price was today hiked by Rs 2.58 a litr...
2,"JUN 01 2016, 10:10 IST","Mumbai, Jun 1, 2016, PTI:,",Business,"Sensex back in green, rises 46 pts on macroeco...","After a day's pause, benchmark Sensex resumed ..."
3,"JUN 01 2016, 10:46 IST","New Delhi, June 1, 2016, PTI:,",Business,ATF price hiked by 9.2%; non-subsidised LPG by...,Aviation turbine fuel or jet fuel price was to...
4,"JUN 01 2016, 12:16 IST","Tokyo, Jun 1, 2016, PTI:,",Business,"Economy on 'upward curve', monsoon, GST to pus...",With India retaining the fastest growing large...
...,...,...,...,...,...
4612,"JUN 29 2016, 00:02 IST","Bengaluru, Jun 29, 2016, DHNS:,",State,Counselling begins for ComedK seats,The counselling for engineering seats under th...
4613,"JUN 29 2016, 00:15 IST","Mysuru, Jun 29, 2016, DHNS,",State,Mysuru doctor dies during Leh expidition,A city-based doctor who was on an expedition t...
4614,"JUN 29 2016, 00:47 IST","New Delhi, Jun 29, 2016, DHNS:,",State,Nirmala promises to address arecanut price cra...,Expressing concern over the crash in domestic ...
4615,"JUN 29 2016, 00:48 IST","Bengaluru, Jun 29, 2016, DHNS:,",State,Deadline for final CET seat options,Candidates applying for CET seats must enter t...
4616,"JUN 29 2016, 21:17 IST","Bengaluru, Jun 29, 2016, PTI,",State,Controversy erupts over direction to buy book ...,"An official direction, authorising government ..."

In [160]:
result1=news.to_csv('DeccanHerald.csv')

In [162]:
result2=news.to_excel(r'C:\Users\eshan\DeccanHerald.xlsx',index=False)

In [163]:
result3=news.to_json(r'C:\Users\eshan\DeccanHerald.json')